source "https://rubygems.org"

gem "haml", "~> 5.2", ">= 5.2.2"
gem "nokogiri", "~> 1.14", ">= 1.14.1"
gem "pg", "~> 1.4", ">= 1.4.5"
gem "puma", "~> 6.0", ">= 6.0.2"
gem "rackup", "~> 2.1", ">= 2.1.0"
gem "rake", "~> 13.0", ">= 13.0.6"
gem "roda", "~> 3.65"
gem "roda-enhanced_logger", "~> 0.5.0"
gem "sequel", "~> 5.65", ">= 5.65.0"
gem "sequel_pg", "~> 1.17", ">= 1.17.1", require: "sequel"

group :development, :test do
  gem "awesome_print", "~> 1.9", ">= 1.9.2"
  gem "dotenv", "~> 2.8", ">= 2.8.1"
  gem "pry-byebug", "~> 3.10", ">= 3.10.1"
end

group :development do
  gem "rerun", "~> 0.14", ">= 0.14.0"
  gem "standard", "~> 1.24", ">= 1.24.0"
end

group :test do
  gem "capybara", "~> 3.38", ">= 3.38.0"
  gem "minitest", "~> 5.17", ">= 5.17.0"
  gem "minitest-reporters", "~> 1.5"
  gem "minitest-hooks", "~> 1.5"
  gem "rack-test", "~> 2.0", ">= 2.0.2"
end
