source "https://rubygems.org"

gem "haml", "~> 5.2", ">= 5.2.2"
gem "nokogiri", "~> 1.13", ">= 1.13.8"
gem "pg", "~> 1.4", ">= 1.4.3"
gem "puma", "~> 5.6", ">= 5.6.5"
gem "rackup", "~> 0.2", ">= 0.2.2"
gem "rake", "~> 13.0", ">= 13.0.6"
gem "roda", "~> 3.60"
gem "roda-enhanced_logger", "~> 0.5.0"
gem "sequel", "~> 5.60", ">= 5.60.01"
gem "sequel_pg", "~> 1.16", require: "sequel"

group :development, :test do
  gem "awesome_print", "~> 1.9", ">= 1.9.2"
  gem "dotenv", "~> 2.8", ">= 2.8.1"
  gem "pry-byebug", "~> 3.10", ">= 3.10.1"
end

group :development do
  gem "rerun", "~> 0.13", ">= 0.13.1"
  gem "standard", "~> 1.16", ">= 1.16.1"
end

group :test do
  gem "capybara", "~> 3.37", ">= 3.37.1"
  gem "minitest", "~> 5.16", ">= 5.16.3"
  gem "minitest-reporters", "~> 1.5"
  gem "minitest-hooks", "~> 1.5"
  gem "rack-test", "~> 2.0", ">= 2.0.2"
end
